### PR TITLE
Explore coffee_boat 

### PR DESCRIPTION
**Pull request by willingc**
- explore the code base
- edits to make code new contributor friendly

### CODE REVIEW

**Comment by holdenk** [comment]
OMG thank you!

**Comment by holdenk** [comment]
I'm going to merge this WIP but use nose for now if that's ok? I've got some changes I'd like to make on top of this. We can back it out if that doesn't end up working out.

**Comment by willingc** [comment]
Sure. No problem @holdenk. Let me rebase and correct the conflicts.

**Comment by willingc** [comment]
@holdenk I've rebased this but now notice that you had based #23 on this. Happy to help clean up any conflicts this causes to #23.

**Review by holdenk — APPROVED** [review]
Thank you! The changes look great :)

**Pull request merged**
