### PR TITLE
add initial circleci config

### PR DESCRIPTION
**Pull request by willingc**
Addresses #26 

This first pass for a config is based on Travis process. We can update and tweak from there to improve Spark simplicity of install, etc.

### CODE REVIEW

**Comment by willingc** [comment]
Still WIP. Will return later...

**Review by rgbkrk — APPROVED** [review]

**Comment by rgbkrk** [comment]
> We can update and tweak from there to improve Spark simplicity of install, etc.

Yeah I think a cool way to do it would be to install / setup spark as an attached container using the same steps. Don't have too though, this seems to work pretty well.

**Review by holdenk — APPROVED** [review]
Awesome. I think this is a great point to do the initial merge but happy to wait too :) Not being entirely dependent on travis is also a bonus :)

**Comment by holdenk** [comment]
Would you be ok with merging it for now and imptoving as we go?

**Comment by rgbkrk** [comment]
💥

**Pull request merged**
