### PR TITLE
Add support for installing Python packages on an existing context

### PR DESCRIPTION
**Pull request by holdenk**
I have a mediocre feeling about this, but for notebook users re-launching the ship everytime they add a new package probably isn't a lot of fun.

### CODE REVIEW

**Comment by holdenk** [comment]
I'll leave this open for ~8 hours incase anyone has comments then I'll just merge otherwise :)

**Comment by rgbkrk** [comment]
Do you want me to squash merge when you're running through exploratory commits? I do the same too and end up squashing mine, it's up to you as the lead on this though. 😄

**Review by willingc — APPROVED** [review]
LGTM. Leaving for airport so will let @rgbkrk merge. Thanks @holdenk. Love the amusing error messages too.

**Comment by holdenk** [comment]
Thanks for merging, and in general I also tend to do squash when merging something exploratory like this :) (Some folks tell me I should squash locally but I like to show the process for if/when I come back to look through the PR and figure out what the hell I did :p)

**Pull request merged**
